export { Plugin_FC_TODAY_BTN } from './today.js'
export { Plugin_FC_SHOW_CALENDAR } from './show_btn.js'
export { Plugin_FC_SELF_PAINT } from './painted.js'
export { Plugin_FC_TABS } from './tabs.js'
export { applyPlugin } from '../mixins/plugin_manager_mixin.mjs'